fail_fast: true
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort -c
        language: system
        types: [file, python]
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [file, python]
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [file, python]
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        files: 'src/snakesheets'
        types: [file, python]
      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        files: 'src/snakesheets/test'
